name: shoppingapp
description: Shopping App
version: 1.0.0

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^0.1.3
  google_fonts: ^1.0.0
  getflutter: ^1.0.11
  validators: ^2.0.0+1
  flutter_icons: ^1.1.0
  flutter_svg: ^0.17.4
  provider: ^3.1.1
  flutter_material_color_picker: ^1.0.5
  shared_preferences: ^0.5.7
  convex_bottom_bar: ^2.1.1
  badges: ^1.1.1
  page_transition: ^1.1.5
  carousel_slider: ^2.1.0
  clippy_flutter: ^1.1.1
  auto_size_text: ^2.1.0
  flutter_rating_bar: ^3.0.1+1
  like_button: ^0.2.0
  flutter_phoenix: ^0.1.0
  flutter_countdown_timer: ^1.1.0
  bubble_tab_indicator: ^0.1.4
  rxdart: ">=0.23.0 <0.24.0"
  expandable: ^4.1.3
  searchable_dropdown: ^1.1.3
  dio: ^3.0.8
  dio_http_cache: ^0.2.5
  html: ^0.14.0+1
  sqflite: any
  scoped_model: ^1.0.1
  timeago: ^2.0.26
  cached_network_image: ^2.0.0
  intl: ^0.16.0
  autocomplete_textfield: ^1.7.3
  google_maps_flutter: ^0.5.11
  geocoder: ^0.2.1
  location: ^2.3.5
  google_sign_in: ^4.1.4
  firebase_auth: ^0.15.4
  firebase_messaging: ^5.0.2
  flutter_facebook_login: ^2.0.1
  country_code_picker: ^1.2.4


dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/icons/
    - assets/i18n/
    - assets/lang/


  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
